version: '3.8'

services:
  builder:
    build: .
    platform: linux/arm64
    command: /bin/sh -c "${COMPILE_CMD:-make PLATFORM=dev build}"
    volumes:
      - minui_build:/work/build
      - ./:/work/src:cached
    environment:
      - COMPILE_CMD

  runner:
    build: .
    platform: linux/arm64
    command: /usr/local/bin/dev-entrypoint.sh --run-tests
    volumes:
      - minui_build:/work/build
      - ./:/work/src:cached
    ports:
      - "5900:5900"
    stdin_open: true
    tty: true

volumes:
  minui_build: {}
