# rgb30
ARCH = -mtune=cortex-a55 -march=armv8.2-a -O3
LIBS = -flto -lrga
SDL = SDL2

# Include Phase 2 feature flags
-include $(WORKSPACE)/rgb30/platform/phase2_flags.mk

# Conditional CFLAGS based on feature flags
ifeq ($(USE_CONFIG_SYSTEM),1)
    CFLAGS += -DUSE_CONFIG_SYSTEM
endif

ifeq ($(USE_GFX_BACKEND),1)
    CFLAGS += -DUSE_GFX_BACKEND
endif

ifeq ($(USE_FBDEV_BACKEND),1)
    CFLAGS += -DUSE_FBDEV_BACKEND
endif

ifeq ($(USE_FRAME_QUEUE),1)
    CFLAGS += -DUSE_FRAME_QUEUE
    LIBS += -lpthread
endif

ifeq ($(DEBUG_PHASE2),1)
    CFLAGS += -DDEBUG_PHASE2
endif
