# miyoomini-toolchain doesn't need to override these
ARCH =
LIBS = -lmi_sys -lmi_gfx -lpthread

# Include Phase 2 feature flags
-include $(WORKSPACE)/miyoomini/platform/phase2_flags.mk

# Conditional CFLAGS based on feature flags
ifeq ($(USE_CONFIG_SYSTEM),1)
    CFLAGS += -DUSE_CONFIG_SYSTEM
endif

ifeq ($(USE_GFX_BACKEND),1)
    CFLAGS += -DUSE_GFX_BACKEND
endif

ifeq ($(USE_FBDEV_BACKEND),1)
    CFLAGS += -DUSE_FBDEV_BACKEND
endif

ifeq ($(USE_FRAME_QUEUE),1)
    CFLAGS += -DUSE_FRAME_QUEUE
    # pthread already in LIBS
endif

ifeq ($(DEBUG_PHASE2),1)
    CFLAGS += -DDEBUG_PHASE2
endif