# rg35xx
ARCH = -marm -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -mcpu=cortex-a53
LIBS = -flto
SDL = SDL2

# Include Phase 2 feature flags
-include $(WORKSPACE)/rg35xxplus/platform/phase2_flags.mk

# Conditional CFLAGS based on feature flags
ifeq ($(USE_CONFIG_SYSTEM),1)
    CFLAGS += -DUSE_CONFIG_SYSTEM
endif

ifeq ($(USE_GFX_BACKEND),1)
    CFLAGS += -DUSE_GFX_BACKEND
endif

ifeq ($(USE_FBDEV_BACKEND),1)
    CFLAGS += -DUSE_FBDEV_BACKEND
endif

ifeq ($(USE_FRAME_QUEUE),1)
    CFLAGS += -DUSE_FRAME_QUEUE
    LIBS += -lpthread
endif

ifeq ($(DEBUG_PHASE2),1)
    CFLAGS += -DDEBUG_PHASE2
endif